CREATE TABLE IF NOT EXISTS rooms(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    discription TEXT,
    price INT,
    creationdate DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS booking(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    roomid INT,
    datestart DATETIME,
    dateend DATETIME
);